### ISSUE TITLE
Data from referenced content type is separated

### ISSUE THREAD

**Issue by jckfa** [contentful/jekyll-contentful-data-import#16]
Hi, I don't know if this is a mapping issue (I've never done any custom mapping before) but here's where I'm at:

I have a Article content type that references an Author content type (allowing multiple authors).
When I import the data, this is what I get:

```
---
article:
- sys:
    id: ...
  title: ...
  author:
  - sys:
      id: ...
  - sys:
      id: ...
  body: ...

author:
- sys:
    id: ...
  name: ...
  dob: ...
- sys:
    id: ...
  name: ...
  dob: ...
```

The author fields "name" and "dob" are not inside article.

I need the data to format like this:
```
---
article:
- sys:
    id: ...
  title: ...
  author:
  - sys:
      id: ...
    name: ...
    dob: ...
  - sys:
      id: ...
    name: ...
    dob: ...
  body: ...
```
That way, I can fetch the data of each author within a particular article.
