### ISSUE TITLE
Non-localized assets seem broken

### ISSUE THREAD

**Issue by felixjung** [contentful/jekyll-contentful-data-import#46]
Hey,

I don't know what happened, but somehow over the past week our build broke. I can't recall updating any dependencies, but we keep getting
```
NoMethodError: undefined method `[]=' for nil:NilClass
```
when trying to fetch from our space.

Doing some digging with `pry` I was able to localize the source of this issue at [contentful.rb/lib/contentful/asset.rb#79](lib/contentful/asset.rb#L79):
```
@fields[default_locale][:file] = ::Contentful::File.new(file_json)
```
For some of our assets used in non-localized entries, `@fields[default_locale]` is `nil`, causing this line to fail. I don't understand the default locale is `nil`, as I would have thought the `FieldsResource` constructor should take care of initializing the default localization, no?

Is this maybe caused by us filtering for the locale we want to work on in the configuration of the Jekyll plugin?

```
  spaces:
    - de-DE:
        space: "xxx"
        access_token: "xxx"
        all_entries: true
        all_entries_page_size: 1000
        cda_query:
          include: 2
          limit: 100
          locale: "de-DE"
        client_options:
          api_url: "cdn.contentful.com"
        destination: "contentful"
```

I tried to quick-and-dirty patch this issue by either ensuring the `@fields[default_locale]` is initialized to an empty hash, if nil, or by directly setting `@fields[:file]` instead. Both ended up causing the following error:
```
NoMethodError: undefined method `url' for #<Hash:0x007fe13bb2c338>
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-contentful-data-import-1.5.0/lib/jekyll-contentful-data-import/mappers/base.rb:119:in `map_asset'
```

Any idea what's going on?
