### ISSUE TITLE
Cannot reduce resolution depth

### ISSUE THREAD

**Issue by clubajax** [contentful/jekyll-contentful-data-import#67]
Regardless of what parameters I try, I cannot reduce the resolution depth. All changes result in the exact same file size.

I'm trying to solve the A links to B, B links to A recursion problem as noted here: https://github.com/contentful/contentful_model/issues/111

It's not obvious if these properties work together, or cancel each other out.
```
contentful_options: &contentful_options
  cda_query:
    include: 2
    limit: 1000
  all_entries: true

contentful:
  spaces:
    -
      pec_staging:
        <<: *contentful_options
        client_options:
          api_url: 'preview.contentful.com'
          max_include_resolution_depth: 2
```

These are the version I am using:

contentful (0.12.0)
contentful-management (2.6.0)
jekyll (3.7.3)
jekyll-assets (2.2.8)
