### ISSUE TITLE
Memory issues?

### ISSUE THREAD

**Issue by djoos** [contentful/jekyll-contentful-data-import#68]
Hi there!

I'm experiencing issues running `Jekyll::Commands::Contentful.process([], {}, Jekyll.configuration['contentful'])` on CircleCI:
```
Starting Contentful import
Exited with code 137

Hint: Exit code 137 typically means the process is killed because it was running out of memory
Hint: Check if you can optimize the memory usage in your app
Hint: Max memory usage of this container is 4287877120
 according to /sys/fs/cgroup/memory/memory.max_usage_in_bytes
```

Running the same locally with the activity monitor open, I see the ruby process consuming a lot of memory as well upon running `jekyll contentful` (gradually builds up to **4GB**!)...
You could think the Contentful space/environment I'm importing from has loads of entries/assets, however, that is not the case: it's only a handful of entries and a couple of assets!

Any help/reference to code that could be optimized for memory purposes in the importer appreciated!

Thanks in advance!
David

P.S. This is making use of v1.7.0 - 1.8.0 is awkwardly complaining upon import ([`Error: undefined method`[]' for nil:NilClass`](https://github.com/contentful/jekyll-contentful-data-import/issues/9)), even though the _config.yml hasn't changed from v1.7.0 usage... (this is obviously a separate issue)

**Comment by dlitvakb** [comment]
Hey @djoos,

Your first issue is occurring due to you having a circular reference in your content model, and this ends up trying to build an extremely large relationship tree, which sprawls into being a huge memory hog.

This can be easily solved by either limiting the maximum depth that tree can take, by reusing the objects within the tree, or by a combination of both.

This can be achieved by passing the following 2 options to the `client_options` section of the configuration block:

```yaml
max_include_resolution_depth: 5 # or any number that makes sense for your use case (say if you need 10 levels of depth, change it to 10)
reuse_entries: true # this will avoid re-creating objects for each encounter of the same entry
```

Regarding your second issue, without a stack trace or access to the space, it's really hard to understand what may be going on. I'd recommend fixing the memory issue first with what I shared above, and afterwards, if the second issue persists, please open a support ticket at https://support.contentful.com and provide me some more details so we can look into what may be causing that issue.

Hope this helps,

Cheers

**Comment by djoos** [comment]
Hi @dlitvakb,

Re: circular reference in the content model
`max_include_resolution_depth:` and `reuse_entries` worked like a treat, thank you!

Re: second issue
The _config.yml is (as used successfully by v1.7.0):
```
contentful:
  spaces:
    - localeone:
        space: heregoesmyspaceid
        access_token: heregoesmyaccesstoken
        environment: heregoesmyenvironment
        cda_query:
          locale: heregoessomelocale
        destination: heregoessomedestination
        client_options:
          api_url: cdn.contentful.com
          max_include_resolution_depth: 3
          reuse_entities: true
    - localetwo:
        space: heregoesmyspaceid
        access_token: heregoesmyaccesstoken
        environment: heregoesmyenvironment
        cda_query:
          locale: heregoessomelocale
        destination: heregoessomedestination
        client_options:
          api_url: cdn.contentful.com
          max_include_resolution_depth: 3
          reuse_entities: true
```
...but when making use of v1.8.0 I get the following output:
```
NoMethodError: undefined method `[]' for nil:NilClass
/path/to/gems/jekyll-contentful-data-import-1.8.0/lib/jekyll-contentful-data-import/importer.rb:74:in `spaces'
/path/to/gems/jekyll-contentful-data-import-1.8.0/lib/jekyll-contentful-data-import/importer.rb:21:in `run'
/path/to/gems/jekyll-contentful-data-import-1.8.0/lib/jekyll/commands/contentful.rb:40:in `process'
```

Thanks again for your help!

Kind regards,
David
