### ISSUE TITLE
Localized Assets

### ISSUE THREAD

**Issue by rmiklautz** [contentful/jekyll-contentful-data-import#71]
Getting the following error:

I am using contentful together with commercelayer and jekyll

jekyll 3.8.5 | Error:  undefined method `each' for nil:NilClass

```

contentful:
  spaces:
    - en-US:
        space: xxx
        access_token: xxxx
        all_entries: true
        cda_query:
          locale: "en-US"
        client_options:
          default_locale: 'en-US'
    - it:
        space: xxx
        access_token: xxx
        all_entries: true
        cda_query:
          locale: "it"
        client_options:
          default_locale: 'en-US' 

```

Any ideas?
