### ISSUE TITLE
Unclear how to do rich_text_mappings

### ISSUE THREAD

**Issue by daimz** [contentful/jekyll-contentful-data-import#72]
I am having a really hard time making heads or tails of the documentation on how to get rich_text_mappings working. Below I have done, but nothing seems to happen, I just get the full `entry` JSON printed where the entry should be, not the `entry.content_type_id`, any guidance would be much appreciated.

Config.yml
```
page_gen:
  - index_files: true
    data: "contentful.spaces.site.blogPost"
    template: "custom-post"
    name: "slug"
    dir: "blog"
    extension: "html"
    rich_text_mappings:
      embedded-entry-block: QcEntryBlockRenderer
```

_plugins/mappers/QcEntryBlockRenderer.rb
```
class QcEntryBlockRenderer < RichTextRenderer::BaseNodeRenderer
  def render(node)
    entry = node['data']['target']

    "<code><pre>{{ entry.content_type_id | jsonify }}</pre></code>"
  end
end
```

looking at this documentation and trying to match with [rich-text-renderer](https://github.com/contentful/rich-text-renderer.rb) I don't know if I need, or not:

```
renderer = RichTextRenderer::Renderer.new(
  'embedded-entry-block' => MyEntryBlockRenderer
)
```
